[package]
name = "bevy_github_ci_template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.8"
kayak_ui = { git="https://github.com/StarArawn/kayak_ui", features = ["bevy_renderer"] }
#rui = "0.3.3"

